name: Publish Python Package

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: pypi

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install uv
      run: |
        pipx install uv

    - name: Build package
      run: |
        uv build --strict

    - name: Publish to PyPI
      run: |
        uv publish dist/*.tar.gz --token $PYPI_TOKEN
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}